; CHECK THE SWITCH STATE AT PORT 0 AND OUTPUT IT TO PORT 1

MOV A,P0 	 ; WHEN THE SWITCH IS PRESSED, THE VALUE READ WILL BE LOW.
MOV R1,A 	 
MOV P1,A	; THE LED WILL LIGHT UP WHEN A LOW PULSE IS APPLIED.

