; TOGGLE EVERY OTHER PIN OF PORT 0

	MOV R1,#55H	; LOAD R1 WITH 55 HEX VALUE
	MOV R2,#0AAH    ; LOAD R2 WITH AA HEX VALUE
BACK:	
	MOV P0,R1 	; P0 <- DATA OF R1
	CALL DELAY 
	MOV P0,R2
	CALL DELAY
	JMP BACK 	; NON-CONDITIONAL JUMP 

; SUBROUTINE FOR DELAY 
DELAY: 
	MOV R0,#0FFH
HERE:   DJNZ R0,HERE 	; DECREMENT AND JUMP IF R0 IS NOT EQUAL TO ZERO 
	RET

//